-- MySQL Script generated by MySQL Workbench
-- Fri Sep 30 15:12:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cliente
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cliente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cliente` DEFAULT CHARACTER SET utf8mb4 ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE `cliente` ;

-- -----------------------------------------------------
-- Table `cliente`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente`.`cidade` (
  `cod_cidade` INT(11) NOT NULL,
  `dcr_cidade` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_cidade`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cliente`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente`.`cliente` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NULL DEFAULT NULL,
  `Cpf` CHAR(11) NULL DEFAULT NULL,
  `Contato` VARCHAR(20) NULL DEFAULT NULL,
  `Data_nasc` DATE NULL DEFAULT NULL,
  `Sexo` CHAR(1) NULL DEFAULT NULL,
  `Bairro` VARCHAR(50) NULL DEFAULT NULL,
  `Cod_cidade` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `Cod_cidade` (`Cod_cidade` ASC) VISIBLE,
  CONSTRAINT `cliente_ibfk_1`
    FOREIGN KEY (`Cod_cidade`)
    REFERENCES `cliente`.`cidade` (`cod_cidade`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
